services:
  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
      - "4000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      anythingllm:
        condition: service_healthy
      ollama:
        condition: service_healthy
    networks:
      - docaiche
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - db_data:/data
    restart: unless-stopped

  web_ui:
    build:
      context: .
      dockerfile: src/web_ui/Dockerfile
    ports:
      - "4080:8080"
    depends_on:
      - api
    networks:
      - docaiche
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis_data:/data
    networks:
      - docaiche
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  db:
    image: nouchka/sqlite3:latest
    command: "tail -f /dev/null"
    environment:
      - SQLITE_DATABASE=app.db
    volumes:
      - db_data:/data
    networks:
      - docaiche
    healthcheck:
      test: ["CMD", "sqlite3", "/data/app.db", ".databases"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  anythingllm:
    image: mintplexlabs/anythingllm:latest
    environment:
      STORAGE_DIR: /app/server/storage
    volumes:
      - anythingllm_data:/app/server/storage
      - anythingllm_exports:/app/server/exports
    networks:
      - docaiche
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - docaiche
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ollama:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

networks:
  docaiche:

volumes:
  redis_data:
  db_data:
  anythingllm_data:
  anythingllm_exports:
  ollama_models: