services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      anythingllm:
        condition: service_healthy
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn src.main:app --host 0.0.0.0 --port 8000
      "
    networks:
      - docaiche
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 5s
      timeout: 4s
      retries: 10
    volumes:
      - db_data:/data
    restart: unless-stopped

  web_ui:
    build:
      context: .
      dockerfile: src/web_ui/Dockerfile
    ports:
      - "4080:8080"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - docaiche
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 4s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis_data:/data
    networks:
      - docaiche
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 4s
      retries: 10
    restart: unless-stopped

  db:
    image: alpine:3.18
    command: ["sh", "-c", "mkdir -p /data && touch /data/docaiche.db && tail -f /dev/null"]
    volumes:
      - db_data:/data
    networks:
      - docaiche
    healthcheck:
      test: ["CMD", "test", "-f", "/data/docaiche.db"]
      interval: 5s
      timeout: 4s
      retries: 10
    restart: unless-stopped

  anythingllm:
    image: mintplexlabs/anythingllm:latest
    environment:
      STORAGE_DIR: /app/server/storage
    volumes:
      - anythingllm_data:/app/server/storage
      - anythingllm_exports:/app/server/exports
    networks:
      - docaiche
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/health"]
      interval: 5s
      timeout: 4s
      retries: 10
    restart: unless-stopped

networks:
  docaiche:

volumes:
  redis_data:
  db_data:
  anythingllm_data:
  anythingllm_exports: