auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info
  # Increase server timeouts for complex queries
  http_server_read_timeout: 600s
  http_server_write_timeout: 600s
  grpc_server_max_recv_msg_size: 8388608  # 8MB
  grpc_server_max_send_msg_size: 8388608  # 8MB

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

ingester:
  wal:
    enabled: true
    dir: /loki/wal
    # Optimize WAL for faster recovery
    checkpoint_duration: 5m
    flush_on_shutdown: true
    replay_memory_ceiling: 512MB
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  # Optimize chunk settings for better performance
  chunk_idle_period: 30m      # Reduced from 1h
  max_chunk_age: 2h           # Increased from 1h
  chunk_target_size: 1572864  # 1.5MB for better compression
  chunk_retain_period: 5m     # Reduced from 30s
  # Increase concurrent flushes
  concurrent_flushes: 16

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-shipper-active
    cache_location: /loki/tsdb-shipper-cache
    cache_ttl: 24h
    # Enable index gateway for better query performance
    index_gateway_client:
      server_address: ""
  filesystem:
    directory: /loki/chunks
  # Add bloom filters for faster queries
  bloom_shipper:
    working_directory: /loki/blooms
    bloom_gateway_client:
      addresses: []

compactor:
  working_directory: /loki/tsdb-shipper-compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: filesystem
  # Enable table manager for automatic retention
  retention_lookback_limit: 0h

limits_config:
  # Optimize retention for performance vs storage
  retention_period: 72h         # Reduced from 168h (7 days to 3 days)
  reject_old_samples: true
  reject_old_samples_max_age: 72h
  # Query performance optimizations
  max_cache_freshness_per_query: 1m    # Reduced from 10m
  split_queries_by_interval: 5m         # Reduced from 15m
  max_query_parallelism: 32            # Increased parallelism
  # Increase rate limits for better throughput
  ingestion_rate_mb: 32                # Doubled from 16
  ingestion_burst_size_mb: 64          # Doubled from 32
  per_stream_rate_limit: 5MB           # Increased from 3MB
  per_stream_rate_limit_burst: 20MB    # Increased from 15MB
  # Query limits
  max_entries_limit_per_query: 10000    # Limit result size
  max_query_length: 0h                  # No limit on query time range
  max_query_lookback: 0h               # No limit on lookback
  max_streams_per_user: 0             # No limit on streams
  max_global_streams_per_user: 0      # No limit on global streams

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  # Enable ruler for recording rules
  enable_sharding: false
  evaluation_interval: 1m
  poll_interval: 1m

analytics:
  reporting_enabled: false

# Query frontend optimizations
query_range:
  # Enable result caching
  results_cache:
    cache:
      # Use embedded cache for single-instance setup
      embedded_cache:
        enabled: true
        max_size_mb: 200      # Increased from 100
        ttl: 1h
  # Cache metadata queries
  cache_results: true
  # Enable query parallelization
  parallelise_shardable_queries: true
  # Optimize query splitting
  split_queries_by_interval: 5m
  # Enable compression
  compress_responses: true

# Frontend optimizations
frontend:
  # Increase concurrency
  max_outstanding_per_tenant: 2048
  # Enable compression
  compress_responses: true
  # Log slow queries for analysis
  log_queries_longer_than: 5s
  # Optimize scheduler
  scheduler_address: ""
  scheduler_dns_lookup_period: 10s
  scheduler_worker_concurrency: 10

# Querier optimizations
querier:
  # Increase concurrent queries
  max_concurrent: 20
  # Use index cache
  query_ingesters_within: 3h
  # Enable at-modifier for better caching
  at_modifier_enabled: true
  # Engine optimizations
  engine:
    timeout: 5m
    max_look_back_period: 0s

# Enable chunk cache
chunk_store_config:
  chunk_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 100
      ttl: 1h
  # Write dedupe cache
  write_dedupe_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 50
      ttl: 1h

# Index queries cache
index_queries_cache_config:
  embedded_cache:
    enabled: true
    max_size_mb: 100
    ttl: 1h

# Enable TSDB index caching
tsdb_shipper:
  index_cache_size: 100MB
  index_cache_validity: 1h

# Memberlist config for better cluster coordination (even single-instance benefits)
memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members: []