server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    # Batch settings to reduce load
    batchwait: 1s
    batchsize: 1048576  # 1MB

scrape_configs:
  # Docker container logs - simplified pipeline
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: dockerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      # Extract basic container info
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      
      # Extract container name only
      - json:
          expressions:
            tag:
          source: attrs
      
      # Parse container name - simplified regex
      - regex:
          expression: '(?P<container_name>[^|]*)'
          source: tag
      
      # Extract service name for DocAIche containers only
      - match:
          selector: '{container_name=~".*docaiche.*"}'
          stages:
            - regex:
                expression: 'docaiche-(?P<service>[^-]+)'
                source: container_name
            - labels:
                service:
      
      # Add timestamp
      - timestamp:
          format: RFC3339Nano
          source: time
      
      # Set minimal labels
      - labels:
          container_name:
      
      # Simple log level extraction
      - match:
          selector: '{service!=""}'
          stages:
            - regex:
                expression: '(?i)(?P<level>ERROR|WARN)'
            - labels:
                level:
      
      # Output
      - output:
          source: output

  # DocAIche API logs - simplified
  - job_name: docaiche_api
    static_configs:
      - targets:
          - localhost
        labels:
          job: docaiche
          service: api
          __path__: /var/log/docaiche/api.log
    
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
      
      - timestamp:
          format: RFC3339Nano
          source: timestamp
      
      - labels:
          level:
      
      - output:
          source: message

  # Admin UI logs - simplified
  - job_name: docaiche_admin
    static_configs:
      - targets:
          - localhost
        labels:
          job: docaiche
          service: admin-ui
          __path__: /var/log/docaiche/admin.log
          
    pipeline_stages:
      - output:
          source: log