groups:
  - name: docaiche_performance_alerts
    interval: 30s
    rules:
      # CPU Alerts
      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total{name=~"docaiche.*"}[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "High CPU usage detected for {{ $labels.name }}"
          description: "Container {{ $labels.name }} has been using more than 80% CPU for 5 minutes (current: {{ $value | humanize }}%)"
          
      - alert: CriticalCPUUsage
        expr: rate(container_cpu_usage_seconds_total{name=~"docaiche.*"}[5m]) * 100 > 95
        for: 2m
        labels:
          severity: critical
          team: platform
        annotations:
          summary: "Critical CPU usage for {{ $labels.name }}"
          description: "Container {{ $labels.name }} is at {{ $value | humanize }}% CPU usage"
          
      # Memory Alerts
      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes{name=~"docaiche.*"} / container_spec_memory_limit_bytes{name=~"docaiche.*"} > 0.85
        for: 5m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "High memory usage for {{ $labels.name }}"
          description: "Container {{ $labels.name }} is using {{ $value | humanizePercentage }} of its memory limit"
          
      - alert: MemoryLimitApproaching
        expr: predict_linear(container_memory_usage_bytes{name=~"docaiche.*"}[30m], 3600) > container_spec_memory_limit_bytes{name=~"docaiche.*"}
        for: 5m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "Memory limit will be reached soon for {{ $labels.name }}"
          description: "Based on current growth rate, {{ $labels.name }} will hit memory limit within 1 hour"
          
      # Container Health Alerts
      - alert: ContainerRestarting
        expr: increase(container_restart_count{name=~"docaiche.*"}[1h]) > 2
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "Container {{ $labels.name }} is restarting frequently"
          description: "Container {{ $labels.name }} has restarted {{ $value }} times in the last hour"
          
      - alert: ServiceDown
        expr: up{job=~"docaiche-api|weaviate|redis|loki|prometheus"} == 0
        for: 2m
        labels:
          severity: critical
          team: platform
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.job }} has been down for more than 2 minutes"
          
      # Performance Degradation Alerts
      - alert: SlowAPIResponse
        expr: histogram_quantile(0.95, rate(loki_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "API response times are degraded"
          description: "95th percentile response time is {{ $value | humanizeDuration }}"
          
      - alert: HighErrorRate
        expr: sum(rate(loki_request_duration_seconds_count{status_code=~"5.."}[5m])) > 0.1
        for: 5m
        labels:
          severity: critical
          team: platform
        annotations:
          summary: "High error rate detected"
          description: "5xx error rate is {{ $value | humanize }} requests/sec"
          
      # Network Issues
      - alert: NetworkErrors
        expr: rate(container_network_transmit_errors_total{name=~"docaiche.*"}[5m]) > 0
        for: 5m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "Network errors detected for {{ $labels.name }}"
          description: "Container {{ $labels.name }} is experiencing network transmission errors"
          
      # Log Volume Alerts
      - alert: ExcessiveLogging
        expr: sum by (service) (rate({job="dockerlogs", service=~"api|admin-ui|weaviate|redis"}[5m])) > 100
        for: 10m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "Excessive logging from {{ $labels.service }}"
          description: "{{ $labels.service }} is generating {{ $value | humanize }} log lines/sec"
          
      # Resource Saturation
      - alert: SystemResourceSaturation
        expr: (avg(rate(container_cpu_usage_seconds_total{name=~"docaiche.*"}[5m]) * 100) > 70) and (avg(container_memory_usage_bytes{name=~"docaiche.*"} / container_spec_memory_limit_bytes{name=~"docaiche.*"}) > 0.7)
        for: 10m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "System resources are becoming saturated"
          description: "Both CPU and memory usage are above 70% across the system"