server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?P<image_name>[^|]+)\|(?P<container_id>[^\s]+))
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
          container_id:
          image_name:
      - output:
          source: output

  # Special job for Docaiche API logs
  - job_name: docaiche_api
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\S+\s+\S+)\s+\[(?P<request_id>\w+)\]\s+(?P<method>\w+)\s+(?P<path>\S+)\s+-\s+(?P<status>Started|Completed\s+\d+)(?:\s+in\s+(?P<duration>[\d.]+)s)?'
      - labels:
          method:
          path:
          request_id:
      - metrics:
          http_request_duration_seconds:
            type: Histogram
            description: "HTTP request duration in seconds"
            source: duration
            config:
              buckets: [0.001, 0.01, 0.1, 0.5, 1.0, 5.0]
    static_configs:
      - targets:
          - localhost
        labels:
          job: docaiche_api
          __path__: /var/lib/docker/containers/*/*log
    
  # Job for AnythingLLM logs
  - job_name: anythingllm
    static_configs:
      - targets:
          - localhost
        labels:
          job: anythingllm
          __path__: /var/lib/docker/containers/*/*log