# DocaiChe MCP Server Configuration Example
# =========================================
# 
# This file contains example configuration for the MCP server.
# Copy to mcp_server.yaml and modify as needed.

# Server identification
server_name: "DocaiChe MCP Server"
server_id: "docaiche-mcp-001"

# Transport configuration
transport_config:
  # Network binding
  bind_host: "localhost"
  bind_port: 3000
  
  # Connection settings
  max_connections: 100
  connection_timeout: 30
  read_timeout: 60
  
  # Performance settings
  compression_enabled: true
  max_message_size: 10485760  # 10MB
  
  # Protocol support
  enable_http2: true
  enable_websocket: true

# Authentication settings
require_authentication: true
require_explicit_consent: true

# OAuth 2.1 configuration
oauth_client_id: "docaiche-mcp-client"
oauth_client_secret: "your-secret-here"
oauth_auth_endpoint: "https://auth.docaiche.com/authorize"
oauth_token_endpoint: "https://auth.docaiche.com/token"
oauth_introspection_endpoint: "https://auth.docaiche.com/introspect"
oauth_revocation_endpoint: "https://auth.docaiche.com/revoke"

# Default permissions for unauthenticated access
default_permissions:
  - "search:public"
  - "resources:read:public"
  - "status:read"

# Audit logging
audit_log_file: "logs/mcp_audit.log"
audit_log_max_size: 104857600  # 100MB
audit_log_retention_days: 90

# Rate limiting
rate_limit_enabled: true
rate_limit_requests_per_minute: 60
rate_limit_burst_size: 10

# Service endpoints (for tool/resource integration)
services:
  # Search service
  search_service_url: "http://localhost:8000/api/v1/search"
  
  # Ingestion service
  ingestion_service_url: "http://localhost:8000/api/v1/ingest"
  
  # Documentation service
  documentation_service_url: "http://localhost:8000/api/v1/docs"
  
  # Collections service
  collections_service_url: "http://localhost:8000/api/v1/collections"
  
  # Health service
  health_service_url: "http://localhost:8000/api/v1/health"
  
  # Feedback service
  feedback_service_url: "http://localhost:8000/api/v1/feedback"

# Cache settings
cache_enabled: true
cache_ttl_seconds: 3600
cache_max_size_mb: 512

# Monitoring and metrics
metrics_enabled: true
metrics_port: 9090
metrics_path: "/metrics"

# Development settings
development_mode: false
enable_debug_endpoints: false
allow_insecure_transport: false

# Feature flags
features:
  enable_streaming: true
  enable_batch_requests: true
  enable_resource_subscriptions: false
  enable_prompt_templates: false

# Logging configuration
logging:
  level: "INFO"
  format: "json"
  output:
    - type: "console"
      level: "INFO"
    - type: "file"
      path: "logs/mcp_server.log"
      level: "DEBUG"
      max_size_mb: 100
      max_files: 10