import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconActivity,
  IconCalendar,
  IconCircle,
  IconClock,
  IconDatabase,
  IconExternalLink,
  IconEye,
  IconFolder,
  IconGlobe,
  IconSearch,
  IconTag,
  IconTrendingUp,
  IconUpload,
  IconUsers,
  IconChartBar,
  IconRobot
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  activity: IconActivity,
  alertCircle: IconAlertTriangle,
  calendar: IconCalendar,
  circle: IconCircle,
  clock: IconClock,
  database: IconDatabase,
  externalLink: IconExternalLink,
  eye: IconEye,
  fileText: IconFileText,
  folder: IconFolder,
  globe: IconGlobe,
  search: IconSearch,
  tag: IconTag,
  trendingUp: IconTrendingUp,
  upload: IconUpload,
  users: IconUsers,
  barChart: IconChartBar,
  bot: IconRobot,
  checkCircle: IconCheck,
  moreHorizontal: IconDotsVertical,
  trash2: IconTrash
};
